name: jamesrahhh
publish_to: 'none' 
version: 1.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-VariableFont_wght.ttf
